### ISSUE TITLE
[youtube] Sign in to confirm you’re not a bot. This helps protect our community 

### ISSUE THREAD

**Issue by FengrunZhang** [Mashiro009/slidespeech_dl#4]
yt-dlp in proces.sh become unavailable[https://github.com/yt-dlp/yt-dlp/issues/10172](url)

**Comment by Mashiro009** [comment]
Maybe the contributors of the yt-dlp are tring to solve this problem. Refer to the following issues: 
[[IMPORTANT]🚨 KNOWN ISSUES/FAQ](https://github.com/yt-dlp/yt-dlp/issues/3766)
[[youtube] Sign in to confirm you’re not a bot. This helps protect our community](https://github.com/yt-dlp/yt-dlp/issues/10128) 
[Authenticate with this oauth2 plugin instead of cookies](https://github.com/coletdjnz/yt-dlp-youtube-oauth2)

**Comment by FengrunZhang** [comment]
> Maybe the contributors of the yt-dlp are tring to solve this problem. Refer to the following issues: [[IMPORTANT]🚨 KNOWN ISSUES/FAQ](https://github.com/yt-dlp/yt-dlp/issues/3766) [[youtube] Sign in to confirm you’re not a bot. This helps protect our community](https://github.com/yt-dlp/yt-dlp/issues/10128) [Authenticate with this oauth2 plugin instead of cookies](https://github.com/coletdjnz/yt-dlp-youtube-oauth2)

Thanks! Solved by [https://github.com/coletdjnz/yt-dlp-youtube-oauth2.git](url).
